twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        user: 'Fabian'

when@test:
    twig:
        strict_variables: true
    globals:
        user: 'Fabian'
